### ISSUE TITLE
Expected release date

### ISSUE THREAD

**Issue by carlosedubarreto** [saidwivedi/TokenHMR#1]
Hello, do you have an estimation when it would be available?
Thanks, it looks great!!!

**Comment by saidwivedi** [comment]
Thank you for the interest in our work :)

We plan to release the full code by end of May. Thank you for your patience and understanding!!

**Comment by carlosedubarreto** [comment]
Thanks a lot.
since we are already here, let me ask, I've been making an addon for blender with other solutions, like 4d humans, WHAM and SLAHMR, and packed everything inside an addon called CEB 4D Humans.

I saw this code is not available for commercial use and I'd like to know if the way I do would be possible to add TokenHMR to this addon.

What I try to do is this, deliver the base addon, with the core funcionalities for free and I make  a full version with other tools like, make IK controls on top of the result, do an automatick smooth feet lock, and so on.

Would it be possible to do the same with TokenHMR? Have a free version and a full one only with tools that I add that are not specific to TokeHMR?

I do that because is a way not only to help other creators on using the project people make available on github but also to find a way to try to fund myself to keep developing. I dont have the huge work that you guys had to create the solution, but man, it a very demanding work, because I also support everyone, even the free users.

So I'm asking to be sure if I'll be able to add it to the toolset.

thanks a lot for the attention an congrats for the great work. 👏

thanks.

**Comment by saidwivedi** [comment]
Thank you for the continued interest :) 
Unfortunately, I won't be able able to answer regarding licensing and commercial use. Please contact [ps-licensing@tue.mpg.d](mailto:ps-licensing@tue.mpg.de) for more information.

**Comment by carlosedubarreto** [comment]
No roblem, thanks I'll contact them.
