### ISSUE TITLE
Question about ablation study on token number

### ISSUE THREAD

**Issue by colincqian** [saidwivedi/TokenHMR#2]
Excellent work! The ablation on token number M shows a great boost in performance. I would like to know whether these M tokens are used to represent SMPL parameter at one frame or to represent SMPL parameters in a certain sequence of frames. (maybe downsampled to M frames)

Thank you in advance for answering.

**Comment by saidwivedi** [comment]
Thank you for your interest in our work :)
The tokens mentioned in Tab.3 of main paper represents SMPL parameters for a single frame.
